### ISSUE TITLE
Crashing on database creation

### ISSUE THREAD

**Issue by Saymite** [VitaliiAndreev/WarThunder_PresetRandomizer#1]
Hello, I've just found out about the PresetRandomizer and tried to set it up.
I've encountered a problem while the program creates a database, it seems that it points to a temp folder in D:\ even tough I specified that the working directory for both the game and war thunder tools are on C:\

Log :
```
2019-11-17 18:23:10.1981 DEBUG / Unpacker : Preparing to unpack "C:\Steam Games\steamapps\common\War Thunder\char.vromfs.bin".
2019-11-17 18:23:10.1981 DEBUG / File Manager : Creating "D:\Software\War Thunder Tools\_temp".
2019-11-17 18:23:10.1981 INFO / Manager : Deleting "1.93.0.56.sqlite3".
2019-11-17 18:23:10.1981 TRACE / File Manager : Deleting "1.93.0.56.sqlite3".
2019-11-17 18:23:10.1981 TRACE / File Manager : File deleted.
2019-11-17 18:23:10.1981 INFO / Manager : "1.93.0.56.sqlite3" deleted.
2019-11-17 18:23:10.8239 FATAL / WPF Client : An error has occurred.
	[System.IO.DirectoryNotFoundException]
		Could not find a part of the path 'D:\Software\War Thunder Tools\_temp'.
			at Client.Wpf.Windows.LoadingWindow.<OnLoaded>d__13.MoveNext()
```

Client.Wpf.Settings:

```
  <WarThunderLocation>C:\Steam Games\steamapps\common\War Thunder</WarThunderLocation>
  <KlensysWarThunderToolsLocation>C:\Users\Orion\Desktop\Warhtund\wt-tools</KlensysWarThunderToolsLocation>

```

**Comment by VitaliiAndreev** [comment]
Hi! Thanks for the report and interest in the app.

That's a path used during development. And it looks like the config file supplied with the 0.2.4.1 release got contaminated. The source code doesn't appear to be carrying any debug data. I've re-uploaded 0.2.4.1 with a clean config file.

I may need more info on how it went down. Did you get a prompt to specify valid paths on startup? Did restarting the app with correct paths set in _Client.Wpf.Settings_ result in the same error?

**Comment by Saymite** [comment]
Yes I did get the prompt, and I changed both to my path.
After setting it on the prompt the program ran and encountered the error mentioned.
I checked Client.Wpf.Settings to see if it had the correct path and indeed it was the correct one.

I'll try running it on the new upload.

**Comment by Saymite** [comment]
The new upload worked! And a noticed a new prompt asking me for language that I never saw before, maybe that is related to the bug too?

**Comment by VitaliiAndreev** [comment]
I see, so there is a bug, all right. I'll try to reproduce it later. For now it seems as though the path was read first from the file and didn't get updated in-memory properly when you changed it. Despite that the path was correctly written to the config file.

That language selection only pops up when there's no language selected - so it is with clean config files. The config you'd got on your first download had language pre-set.

**Comment by VitaliiAndreev** [comment]
I've reproduced the bug and fixed it. That kind of situation shouldn't occur again. The fix will be included in the next release.
