### ISSUE TITLE
Localization keys not found

### ISSUE THREAD

**Issue by Czarek422** [VitaliiAndreev/WarThunder_PresetRandomizer#2]
W.T.P.R. doesn't start up after initialization. It says "the given key was not present in the dictionary".
[Log_2020-04-14_13-56-19.log](https://github.com/VitaliiAndreev/WarThunder_PresetRandomizer/files/4475103/Log_2020-04-14_13-56-19.log)

**Comment by VitaliiAndreev** [comment]
The issue is that there's no fallback icon for vehicle classes that aren't identified. And space suits don't follow any class definition pattern encountered previously.

I've made a [hotfix release](https://github.com/VitaliiAndreev/WarThunder_PresetRandomizer/releases/tag/0.2.6.2). Should be okay.

**Comment by Czarek422** [comment]
I confirm, hotfix fixed the problem.
